eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
        - id: Item-service
          uri: lb://Item-service
          predicates:
            - Path=/Item/**
       